import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    appName: 'Berkat Foodbank',
    tagline: 'Reducing Waste, Feeding Hope',
    home: 'Home',
    myRegistrations: 'My Registrations',
    manageEvents: 'Manage Events',
    profile: 'Profile',
    login: 'Login with Google',
    logout: 'Logout',
    register: 'Register',
    upcoming: 'Upcoming',
    ongoing: 'Ongoing',
    completed: 'Completed',
    expired: 'Expired',
    quota: 'Quota',
    full: 'Full',
    registered: 'Registered',
    available: 'Available',
    location: 'Location',
    dateTime: 'Date & Time',
    organizer: 'Organizer',
    contact: 'Contact',
    searchPlaceholder: 'Search events...',
    filterState: 'State',
    filterDistrict: 'District',
    filterTaman: 'Taman',
    registrationForm: 'Registration Form',
    fullName: 'Full Name (as per IC)',
    phoneNumber: 'Phone Number',
    icNumber: 'IC Number',
    submit: 'Confirm Registration',
    estimatedTime: 'Your Estimated Collection Time',
    queueNote: 'Please arrive slightly early. Estimated time is based on 8 mins per person.',
    attended: 'Attended',
    notAttended: 'Awaiting',
    checkIn: 'Check-in',
    beneficiaries: 'Beneficiaries',
    noEvents: 'No upcoming events in this area.',
    eventDetails: 'Event Details',
    totalQuota: 'Total Quota',
    remaining: 'Remaining',
    createEvent: 'Create New Event',
    editEvent: 'Edit Event',
    deleteEvent: 'Delete Event',
    title: 'Title',
    description: 'Description',
    date: 'Date',
    startTime: 'Start Time',
    tamanHelp: 'People can follow their preferred Tamans to receive notifications.',
    malaysiaStates: ['Johor', 'Kedah', 'Kelantan', 'Melaka', 'Negeri Sembilan', 'Pahang', 'Perak', 'Perlis', 'Pulau Pinang', 'Sabah', 'Sarawak', 'Selangor', 'Terengganu', 'Kuala Lumpur', 'Labuan', 'Putrajaya']
  },
  ms: {
    appName: 'Berkat Foodbank',
    tagline: 'Kurangkan Pembaziran, Kongsi Rezeki',
    home: 'Laman Utama',
    myRegistrations: 'Pendaftaran Saya',
    manageEvents: 'Urus Acara',
    profile: 'Profil',
    login: 'Log Masuk dengan Google',
    logout: 'Log Keluar',
    register: 'Daftar',
    upcoming: 'Akan Datang',
    ongoing: 'Sedang Berlangsung',
    completed: 'Selesai',
    expired: 'Tamat Tempoh',
    quota: 'Kuota',
    full: 'Penuh',
    registered: 'Telah Daftar',
    available: 'Tersedia',
    location: 'Lokasi',
    dateTime: 'Tarikh & Masa',
    organizer: 'Penganjur',
    contact: 'Hubungi',
    searchPlaceholder: 'Cari acara...',
    filterState: 'Negeri',
    filterDistrict: 'Daerah',
    filterTaman: 'Taman',
    registrationForm: 'Borang Pendaftaran',
    fullName: 'Nama Penuh (seperti IC)',
    phoneNumber: 'Nombor Telefon',
    icNumber: 'Nombor IC',
    submit: 'Sahkan Pendaftaran',
    estimatedTime: 'Anggaran Waktu Kutipan Anda',
    queueNote: 'Sila tiba lebih awal. Anggaran waktu berdasarkan 8 minit setiap orang.',
    attended: 'Hadir',
    notAttended: 'Menunggu',
    checkIn: 'Daftar Masuk',
    beneficiaries: 'Penerima Manfaat',
    noEvents: 'Tiada acara akan datang di kawasan ini.',
    eventDetails: 'Butiran Acara',
    totalQuota: 'Jumlah Kuota',
    remaining: 'Baki',
    createEvent: 'Buat Acara Baru',
    editEvent: 'Kemas Kini Acara',
    deleteEvent: 'Padam Acara',
    title: 'Tajuk',
    description: 'Penerangan',
    date: 'Tarikh',
    startTime: 'Waktu Mula',
    tamanHelp: 'Orang ramai boleh mengikuti Taman pilihan untuk menerima notifikasi.',
    malaysiaStates: ['Johor', 'Kedah', 'Kelantan', 'Melaka', 'Negeri Sembilan', 'Pahang', 'Perak', 'Perlis', 'Pulau Pinang', 'Sabah', 'Sarawak', 'Selangor', 'Terengganu', 'Kuala Lumpur', 'Labuan', 'Putrajaya']
  },
  zh: {
    appName: '福泽粮仓 (Berkat Foodbank)',
    tagline: '减少浪费，共享福分',
    home: '首页',
    myRegistrations: '我的登记',
    manageEvents: '管理活动',
    profile: '个人资料',
    login: '使用 Google 登录',
    logout: '退出登录',
    register: '登记',
    upcoming: '即将开始',
    ongoing: '进行中',
    completed: '已完成',
    expired: '已过期',
    quota: '配额',
    full: '已满',
    registered: '已登记',
    available: '名额',
    location: '地点',
    dateTime: '日期与时间',
    organizer: '主办方',
    contact: '联系方式',
    searchPlaceholder: '搜索活动...',
    filterState: '州属',
    filterDistrict: '县/区',
    filterTaman: '花园/社区',
    registrationForm: '登记表',
    fullName: '全名 (根据身份证)',
    phoneNumber: '电话号码',
    icNumber: '身份证号码',
    submit: '确认登记',
    estimatedTime: '您的预计领取时间',
    queueNote: '请稍微提前到达。预计时间基于每人 8 分钟计算。',
    attended: '已领取',
    notAttended: '等待中',
    checkIn: '签到',
    beneficiaries: '受惠名单',
    noEvents: '该地区暂无即将举行的活动。',
    eventDetails: '活动详情',
    totalQuota: '总配额',
    remaining: '剩余',
    createEvent: '发布新活动',
    editEvent: '编辑活动',
    deleteEvent: '删除活动',
    title: '标题',
    description: '描述',
    date: '日期',
    startTime: '开始时间',
    tamanHelp: '用户可以关注偏好的社区以接收通知。',
    malaysiaStates: ['柔佛', '吉打', '吉兰丹', '马六甲', '森美兰', '彭亨', '霹雳', '玻璃市', '槟城', '沙巴', '砂拉越', '雪兰莪', '登嘉楼', '吉隆坡', '纳闽', '布城']
  }
};
